# Generated by Django 2.2.5 on 2019-09-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190916_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='user',
            new_name='user_id',
        ),
    ]
