# Generated by Django 2.2.5 on 2019-09-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190916_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
