# Generated by Django 2.2.5 on 2019-09-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190916_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user_id',
        ),
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='book.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
