# Generated by Django 2.2.5 on 2019-09-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190916_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_cbook', to='book.Users'),
        ),
        migrations.AlterField(
            model_name='books',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='book.Users'),
        ),
    ]
